[project]
name = "drprojver"
version = "0.1.0"
description = "Set a version for Davinci ResolveÂ® project files."
requires-python = ">=3.14.2"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.12.0",
]

[tool.black]
line-length = 120
target-version = ['py314']
